### ISSUE TITLE
Raygun crashes the game upon using it on inmate

### ISSUE THREAD

**Issue by M0nk3yking001** [CanInBad/HypertusMod#1]
Hi there, I've downloaded the updated version of this mod and first time that I used it on an inmate it crashed my game. Oh and I have a little idea for your mod, think of it Hyper pregnancy without having to adjust it in the settings or using heat and breeder pills.

**Comment by CanInBad** [comment]
Please provide the following,
A) What part did you resize
B) Is it in combat or in the sexual action
C) Does the immate have any hyperable par

If you can, can you provide log that's provided by the game when you launch the game via command line? Just copy the error logs

As for your idea, I recommend putting it in seperate issue as a feature request, thank you

**Comment by CanInBad** [comment]
disregard last comment, I just done bunch of testing and nothing seem to be crashing with intended breasts size range. Will wait for more info.
I will put a limit when resizing in sexual activities first since that wasn't there the first time.

**Comment by CanInBad** [comment]
fixed in 4c83771d01d896142a8e5c42f017105499b5fdd4 and 17229e11b5471e4faf260d95ce040cef721b0ed2

**Comment by CanInBad** [comment]
Tracking when you can get your updated mod on the mod browser here: https://github.com/Alexofp/BDCCMods/pull/19
