### ISSUE TITLE
Bodyparts compatibility layers aren't registered/working and casuing crash to NPC

### ISSUE THREAD

**Issue by DarkMessiahx** [CanInBad/HypertusMod#18]
species Compatibility layer R3 causes crashes when trying to load parts onto npcs. In my previous post i reported that hypertus no longer sees parts from other mods as hyperable, seems like it causes a crash whenever a dynamic npc tries to equip a hyperable part through species compatibility layer. Seems like  the mod sees that the other mods are installed but for whatever reason cannot load those parts as hyperable which causes a crash whenever an npc generates with said parts. The log file's last entry before the crash is:

addDynamicCharacter(): Adding dynamicnpc0 character No stack available
[RopeBunny, BreedingStock]
ERROR: bodypart with the id avianpenishyperable wasn't found

As in my last post, i'd like to say that R6-1 loaded everything fine.

**Comment by CanInBad** [comment]
Please try again with R6-2

**Comment by DarkMessiahx** [comment]
The problem i believe is that hypertus R6-2 cannot recognize mod parts and convert them into hyperable versions even though it sees the mods just fine and recognizes that they're installed. i have attached the entire log file this time. R6-1 worked fine. 

[godot.log](https://github.com/user-attachments/files/18239924/godot.log)

**Comment by Fox2Code** [comment]
> Hyper tree is null???? send save file to the dev -CanInBad

and

> addDynamicCharacter(): Adding dynamicnpc0 character No stack available

Please send out a copy of your save file.

**Comment by DarkMessiahx** [comment]
Ill try to get a game going where it doesn't crash instantly after pressing the wake up button(no npcs with hyperable parts generate). Btw, i must say one more thing, i did try launching the game with only hypertus, foxlib and compatible parts mods.

Save attached.

[new save.zip](https://github.com/user-attachments/files/18240037/new.save.zip)

**Comment by CanInBad** [comment]
@DarkMessiahx I haven't try your save yet, the reason why hyperable parts don't exist because it uses Module's register function and I careless-ly move the function that add bodyparts to registration past the registration phase. https://github.com/CanInBad/HypertusMod/commit/d01f72b58dee6e4a64ad9075c18a09fe0169125c attempts to fix that and when I test it works on my machine™

Please try this [HypertusP6-3.zip](https://github.com/user-attachments/files/18245453/HypertusP6-3.zip) or the commit mentioned to see if its fixed

if its fixed please close the issue with a tag comment to me, else keep this up.

I will come check again tomorrow evening (8-9pm) my time.

**Comment by DarkMessiahx** [comment]
Everything works perfectly, still getting the (Hyper tree is null???? send save file to the dev -CanInBad) thing in the log but now every part shows up as selectable, and npcs can generate just fine, started a new game 10 times just to be safe and didn't crash at all, all npcs generated, no errors, other then the hyper tree is null one, which i have absolutely no idea about what effect it actually has on the game, as my hyper skill tree works just fine, so it must be something related to npcs but i cant for my life figure out what.

Anyways, my main issues (the crash and missing parts) were fixed with the preview build linked above, thank you! 

I will close this as the main issue in my op post has been fixed but you may want to look into that hyper tree is null error the log gives and what problems it's causing. Other then that, thx for the swift fix.
