### ISSUE TITLE
Tera Breasts unavailable 

### ISSUE THREAD

**Issue by Rocky9ax** [CanInBad/HypertusMod#7]
I cannot select and purchase tera breasts skill in the mod tree, regardless of all other skills maxed.

**Comment by CanInBad** [comment]
fixed in d5452dc39b1af117c3e6fa016d7bda0ad7e2a9ed which is coming up today

**Comment by CanInBad** [comment]
You'll have to look out on [Alexofp/BDCCMods's pull request](https://github.com/alexofp/bdccmods/pulls) when I publicly release the fix

**Comment by CanInBad** [comment]
@Rocky9ax https://github.com/Alexofp/BDCCMods/pull/51
